server:
  port: 8081
  servlet:
    context-path: /springboot

hibernate:
  packages:
    scan: com.sunny.practice.entity
  hbm2ddl:
    auto: none


spring:
  application:
    name: springboot
# jpa
  jpa:
    database : MYSQL
    properties:
      packagesToScan: com.sunny.practice.entity
      hibernate:
        dialect : org.hibernate.dialect.MySQL5Dialect
        show_sql : true
        format_sql: false
        jdbc:
          fetch_size: 100
          batch_size: 100
        connection:
          autocommit: true
          release_mode: auto
          current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

# 数据源配置
  datasource:
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://39.108.239.226:3306/sunny_springboot?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: root
      connection-test-query: select 1
      connection-timeout: 60000
      auto-commit: false
      minimum-idle: 1
      max-lifetime: 1
      maximum-pool-size: 8
      data-source-properties:
        cache-prep-stmts: true
        prep-stmt-cache-size: 250
        prep-stmt-cache-sql-limit: 2048
        use-server-prep-stmts: true


  #redis配置
  redis:
    host: localhost # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 0 # 连接超时时间（毫秒）

#swagger2
swagger:
  basePackage: com.sunny.practice.controller
  title: springboot
