package com.sunny.practice.dao.mybatis.mapper;

import com.sunny.practice.entity.vo.STBUser;

public interface STBUserMapper extends  IBaseMapperDao<STBUser,Long>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_tb_user
     *
     * @mbg.generated Wed Sep 05 23:05:47 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_tb_user
     *
     * @mbg.generated Wed Sep 05 23:05:47 CST 2018
     */
    int insert(STBUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_tb_user
     *
     * @mbg.generated Wed Sep 05 23:05:47 CST 2018
     */
    int insertSelective(STBUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_tb_user
     *
     * @mbg.generated Wed Sep 05 23:05:47 CST 2018
     */
    STBUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_tb_user
     *
     * @mbg.generated Wed Sep 05 23:05:47 CST 2018
     */
    int updateByPrimaryKeySelective(STBUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_tb_user
     *
     * @mbg.generated Wed Sep 05 23:05:47 CST 2018
     */
    int updateByPrimaryKey(STBUser record);
}