package com.sunny.practice.entity.vo;

import java.util.Date;

public class STBUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_tb_user.id
     *
     * @mbg.generated Wed Sep 05 23:05:47 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_tb_user.user_name
     *
     * @mbg.generated Wed Sep 05 23:05:47 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_tb_user.user_password
     *
     * @mbg.generated Wed Sep 05 23:05:47 CST 2018
     */
    private String userPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_tb_user.gender
     *
     * @mbg.generated Wed Sep 05 23:05:47 CST 2018
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_tb_user.tel_phone
     *
     * @mbg.generated Wed Sep 05 23:05:47 CST 2018
     */
    private String telPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_tb_user.del_flag
     *
     * @mbg.generated Wed Sep 05 23:05:47 CST 2018
     */
    private String delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_tb_user.create_time
     *
     * @mbg.generated Wed Sep 05 23:05:47 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_tb_user.update_time
     *
     * @mbg.generated Wed Sep 05 23:05:47 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_tb_user.del_time
     *
     * @mbg.generated Wed Sep 05 23:05:47 CST 2018
     */
    private Date delTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_tb_user.remark
     *
     * @mbg.generated Wed Sep 05 23:05:47 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_tb_user.id
     *
     * @return the value of s_tb_user.id
     *
     * @mbg.generated Wed Sep 05 23:05:47 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_tb_user.id
     *
     * @param id the value for s_tb_user.id
     *
     * @mbg.generated Wed Sep 05 23:05:47 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_tb_user.user_name
     *
     * @return the value of s_tb_user.user_name
     *
     * @mbg.generated Wed Sep 05 23:05:47 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_tb_user.user_name
     *
     * @param userName the value for s_tb_user.user_name
     *
     * @mbg.generated Wed Sep 05 23:05:47 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_tb_user.user_password
     *
     * @return the value of s_tb_user.user_password
     *
     * @mbg.generated Wed Sep 05 23:05:47 CST 2018
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_tb_user.user_password
     *
     * @param userPassword the value for s_tb_user.user_password
     *
     * @mbg.generated Wed Sep 05 23:05:47 CST 2018
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_tb_user.gender
     *
     * @return the value of s_tb_user.gender
     *
     * @mbg.generated Wed Sep 05 23:05:47 CST 2018
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_tb_user.gender
     *
     * @param gender the value for s_tb_user.gender
     *
     * @mbg.generated Wed Sep 05 23:05:47 CST 2018
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_tb_user.tel_phone
     *
     * @return the value of s_tb_user.tel_phone
     *
     * @mbg.generated Wed Sep 05 23:05:47 CST 2018
     */
    public String getTelPhone() {
        return telPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_tb_user.tel_phone
     *
     * @param telPhone the value for s_tb_user.tel_phone
     *
     * @mbg.generated Wed Sep 05 23:05:47 CST 2018
     */
    public void setTelPhone(String telPhone) {
        this.telPhone = telPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_tb_user.del_flag
     *
     * @return the value of s_tb_user.del_flag
     *
     * @mbg.generated Wed Sep 05 23:05:47 CST 2018
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_tb_user.del_flag
     *
     * @param delFlag the value for s_tb_user.del_flag
     *
     * @mbg.generated Wed Sep 05 23:05:47 CST 2018
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_tb_user.create_time
     *
     * @return the value of s_tb_user.create_time
     *
     * @mbg.generated Wed Sep 05 23:05:47 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_tb_user.create_time
     *
     * @param createTime the value for s_tb_user.create_time
     *
     * @mbg.generated Wed Sep 05 23:05:47 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_tb_user.update_time
     *
     * @return the value of s_tb_user.update_time
     *
     * @mbg.generated Wed Sep 05 23:05:47 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_tb_user.update_time
     *
     * @param updateTime the value for s_tb_user.update_time
     *
     * @mbg.generated Wed Sep 05 23:05:47 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_tb_user.del_time
     *
     * @return the value of s_tb_user.del_time
     *
     * @mbg.generated Wed Sep 05 23:05:47 CST 2018
     */
    public Date getDelTime() {
        return delTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_tb_user.del_time
     *
     * @param delTime the value for s_tb_user.del_time
     *
     * @mbg.generated Wed Sep 05 23:05:47 CST 2018
     */
    public void setDelTime(Date delTime) {
        this.delTime = delTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_tb_user.remark
     *
     * @return the value of s_tb_user.remark
     *
     * @mbg.generated Wed Sep 05 23:05:47 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_tb_user.remark
     *
     * @param remark the value for s_tb_user.remark
     *
     * @mbg.generated Wed Sep 05 23:05:47 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}